# Generated by Django 4.0 on 2021-12-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'langs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('count_cycles', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opers',
                'managed': False,
            },
        ),
    ]
