# Generated by Django 3.2.9 on 2021-12-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название оператора')),
                ('count_cycles', models.IntegerField(verbose_name='Количество тактов ЦП')),
            ],
            options={
                'db_table': 'Operator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proglang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название языка')),
            ],
            options={
                'db_table': 'ProgLang',
                'managed': False,
            },
        ),
    ]
