# Generated by Django 3.2.9 on 2021-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='Производитель')),
                ('flavor', models.CharField(max_length=20, verbose_name='Вкус')),
            ],
        ),
    ]
