# Generated by Django 4.0 on 2021-12-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descr', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'langs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'opers',
                'managed': False,
            },
        ),
    ]
